# Generated by Django 4.2.7 on 2024-02-27 16:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP', unique=True)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('description', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
