# Generated by Django 4.2.7 on 2024-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prot',
            old_name='name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='prot',
            name='fname',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
