# Generated by Django 5.0.2 on 2024-03-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0003_client_education_experience_skill_alter_prot_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
